kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name:  {{ .Values.github_actions_sa.role_name }}
rules:
  - resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - resources:
      - namespaces
      - projects
    verbs:
      - get
  - resources:
      - secrets
      - serviceaccounts
      - pods/exec
      - pods
      - configmaps
      - replicationcontrollers
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources: 
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authorization.openshift.io
    resources: 
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
